version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: utility-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src/keys:/app/src/keys
    networks:
      - utility-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: utility-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - utility-network

networks:
  utility-network:
    driver: bridge
