# -------- Stage 1: Build Backend --------
FROM node:20 AS builder

WORKDIR /app

COPY backend/package*.json ./
RUN npm ci

COPY backend ./  
RUN npm run build

# -------- Stage 2: Production --------
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules


RUN npm rebuild sqlite3

ENV NODE_ENV=production
ENV PORT=7000

EXPOSE 7000
CMD ["node", "dist/src/main.js"]
